SELECT * FROM customer
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS "Total Revenue Generated" FROM customer
GROUP BY gender;

--Q2. Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

--Q3. What are the top 5 products with the highest average rating?
SELECT item_purchased, ROUND(AVG(review_rating)::NUMERIC,2) AS "Average Rating" FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shiping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM customer
WHERE shipping_type IN('Express','Standard')
GROUP BY shipping_type;

--Q5. Do subscribed customersspend more? compare average spend and total revenue between subscribers and
-- non-subscribers.
SELECT subscription_status , COUNT(customer_id) AS "Total Customers" ,
ROUND(AVG(purchase_amount),2) AS "Average Spend",
SUM(purchase_amount) AS "Total Revenue" FROM customer
GROUP BY subscription_status;

--Q6 What 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)), 2) AS percentage_of_purchases_with_discounts
FROM customer
GROUP BY item_purchased
ORDER BY percentage_of_purchases_with_discounts DESC
LIMIT 5;

--Q7. Segment Customers into New, Returning, and Loyal based on their total number of
-- previous purchases, and show the count of each segment.
WITH customer_type AS(
SELECT customer_id, previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)

SELECT customer_segment, COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;


--Q8. What are the top 3 most purchased product with each catrgory?
WITH item_counts AS(
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Which custoemrs are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) as repeat_buyers FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;